### ISSUE TITLE
Multiworld addon not on Scarab

### ISSUE THREAD

**Issue by Hydroptix** [Shadudev/HollowKnight.MultiWorld#16]
Was just trying to play Multiworld with some friends for the first time, but it's not listed on Scarab. I'm down to install it manually, but the installation instructions don't say how to do that.

Attached a screenshot searching for "MultiWorld" in the current version of Scarab.

![image](https://user-images.githubusercontent.com/8387968/162662337-cbf3663f-0f15-442b-9435-935eff9b32d0.png)

**Comment by Shadudev** [comment]
T'is not an issue, since MultiWorld is yet to be released.

**Comment by Shadudev** [comment]
if you wish to play multiworld anyways, you can downgrade your hollow knight to 1.4.3.2, install rando3 and multiworld for that version. Then, setup your own MultiWorldServer from the appropriate MultiWorld release since the public servers are updated to rando4 and multiworld tests
