### ISSUE TITLE
BenchSync?

### ISSUE THREAD

**Issue by ShadiestGoat** [Shadudev/HollowKnight.MultiWorld#24]
Hello! I'd love a feature that would sync available benches with itemsync & benchwarp! Is this possible?

**Comment by Shadudev** [comment]
Given [BenchRando](https://github.com/homothetyhk/BenchRando), you can choose to randomize benches and these will sync between players. As much as I'm aware, it is not possible to make it so benches are items but they're placed vanilla at the moment.
Perhaps something to ask for on the BenchRando's git 👍 
In general, mods like RandoPlus sometimes have a setting called `Define Refs` which adds the custom items to the pool, but doesn't explicitly say they should be randomized. I believe BenchRando will implement something similar for this case
