### ISSUE TITLE
Docs: give <item>

### ISSUE THREAD

**Issue by ShadiestGoat** [Shadudev/HollowKnight.MultiWorld#26]
Hello! On the ItemSync README, it says I can use the give command to give an <item>. How can I get the name of the item? Is it the name in the save file? Eg. for pale ore, would it be "ore"?

**Comment by Shadudev** [comment]
Hey, this part is relevant to the server. If you wish to give yourself items, I can recommend using DebugMod.
For future reference, I will say that questions and recommendations that aren't bugs are more appropriate to be sent on Discord in [Hollow Knight Speedrun Community](https://discord.gg/3JtHPsBjHD), specifically in the #rando-general text channel where many more can provide you with answers.

**Comment by Shadudev** [comment]
For the item name itself, you'd need to match it from [here](https://github.com/homothetyhk/HollowKnight.ItemChanger/blob/master/ItemChanger/Resources/items.json)
