### ISSUE TITLE
Permanent Connecting 

### ISSUE THREAD

**Issue by GabeReal9** [Shadudev/HollowKnight.MultiWorld#28]
My friend and I are trying to use ItemSync, but everytime we try to connect to the Server started by the creators, it infinitely gets stuck on Connecting. Anybody have an idea of how to fix this?

**Comment by Shadudev** [comment]
Hi, thank you for letting me know. Due to memory limitations on the server, it had to be restarted. If it ever happens again, you could @ me on discord Shadu#4196
You can tag me if you are in the Hollow Knight discord server
