### ISSUE TITLE
ItemSync not reconnecting on server reload

### ISSUE THREAD

**Issue by fifiinart** [Shadudev/HollowKnight.MultiWorld#48]
ItemSync v2.7.0

ItemSync doesn't work when reconnecting to a save.

Sync worked fine for us when starting a new game, but on reconnecting to the save, ItemSync stops working and no items get synced.

Is there a fix for this, or do we have to start a new save together to use ItemSync?

**Comment by AziDesigns** [comment]
You dont have to make a new save normally. When I try to Ping the server it is not reachable

I think the server is down. I was trying to follow the guide to install my own server but there is no releases folder with a .exe or .zip in it either so I cant figure out how to do that either.

Was working fine on old saves until today.

**Comment by Shadudev** [comment]
Hey, seems like the AWS instance had some issue. Server restarted so you should be able to successfully reload the ItemSync save and continue your gameplay. Sorry for the inconvenience.

Generally, I would recommend pinging me on some Hollow Knight discord servers if you believe the server has issues in the future.
I tend to keep an eye on `Hollow Knight Speedrun Community` specifically, and many other ItemSync and MultiWorld players are active there too so may be of help in case of future issues 🙏

**Comment by AziDesigns** [comment]
Oh good to know!! I have some questions and would love to msg you on discord. What's your username?

**Comment by Shadudev** [comment]
_shadu is my discord handle, feel free to message me anytime 👍
