### ISSUE TITLE
Enabling mod for existing rando save (ItemSync)

### ISSUE THREAD

**Issue by Jacob1Tm** [Shadudev/HollowKnight.MultiWorld#50]
Friend and i started rando run without mod enabled is it possible to enable it to already existing save?

**Comment by Shadudev** [comment]
Sorry, but it isn't possible.
You must start your ItemSync/MultiWorld game through the appropriate menus after generating the randomizer. 
This is done to ensure you and your friends are going through the required setup and verifications before starting a MultiWorld or ItemSync game together.
