### ISSUE TITLE
DataReceivedEvent.FromID always 0?

### ISSUE THREAD

**Issue by wdghzym** [Shadudev/HollowKnight.MultiWorld#51]
public class DataReceivedEvent
    {
        public readonly int FromID;
        public DataReceivedEvent(string label, string content, string from)
        {
            Label = label;
            Content = content;
            From = from;
            Handled = false;
        }

**Comment by Shadudev** [comment]
Probably some leftover field, I'll remove it. cheers for noticing 👌

**Comment by wdghzym** [comment]
my some mod use itemsync
if my mod need the player ID
use the DataReceivedEvent.From to search/inquire?

**Comment by Shadudev** [comment]
Yes. The server prevents multiple players for having the same name, so consider it as unique
